config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrades, only: [:new, :create]
  devise_for :users
  get 'about' => 'welcome#about'
  get 'blocipedia' => 'welcome#index'
  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/amount.rb
class Amount < ChargesController
  def self.default
    15_00
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators
  has_many :wiki_collaborations, through: :collaborators, source: :wiki

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :default_role

  enum role: [:standard, :premium, :admin]

  private

  def default_role
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    slug.nil? || title_changed?
  end

  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators, source: :user

  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Membership - #{current_user.email}",
      amount: Amount.default
    }
  end
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Blocipedia Membership - #{current_user.email}",
      currency: 'usd'
    )

    # current_user.update_attribute(:standard, false)
    current_user.premium!

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def update
    @wiki = Wiki.friendly.find(params[:wiki_id])
    authorize @wiki
    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki page. Please try again."
      render :edit
    end
  end

  def create
    user = User.find_by_email(params[:collaborator][:user])
    @wiki = Wiki.friendly.find(params[:wiki_id])
    if @wiki.users.include?(user)
      flash[:alert] = "#{user.email} has already been added as a collaborator"
      redirect_to edit_wiki_path(@wiki)
    else
      if Collaborator.create(user_id: user.id, wiki_id: @wiki.id)
        flash[:notice] = "#{user.email} is now a collaborator"
      else
        flash[:alert] = "#{user.email} was not added as a collaborator"
      end
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def destroy
    user = User.find(params[:user_id])
    @wiki = Wiki.friendly.find(params[:wiki_id])
    collaborator = Collaborator.find_by(params[:user_id])
    if collaborator.destroy
      flash[:notice] = "Collaborator: #{collaborator.user.email} has been removed"
    else
      flash[:alert] = "Collaborator: #{collaborator.user.email} has not been removed"
    end
    redirect_to edit_wiki_path(@wiki)
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def new
  end

  def create
    if current_user.transaction do
      current_user.standard!
      current_user.wikis.update_all(private: false)
    end
    flash[:notice] = "You have successfully downgraded your account " +
      "and your private wikis are now public"
  else
    flash[:notice] = "There was an error downgrading your account, " +
      "please try again"
  end
  redirect_to root_path
end

app/controllers/downgrades_controller.rb
class DowngradesController < ApplicationController
  def new
  end

  def create
    if current_user.transaction do
      current_user.standard!
      current_user.wikis.update_all(private: false)
    end
    flash[:notice] = "You have successfully downgraded your account " +
      "and your private wikis are now public"
    else
    flash[:notice] = "There was an error downgrading your account, " +
      "please try again"
    end

    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @user = current_user
    if @user.admin?
      @wikis = Wiki.all
    elsif @user.premium?
      @wikis = Wiki.where(private: false) | @user.wiki_collaborations | @user.wikis
    elsif @user.standard?
      @wikis = Wiki.where(private: false) | @user.wiki_collaborations
    else
      @wikis = Wiki.where(private: false)
    end
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @user = current_user
    @wiki = Wiki.friendly.find(params[:id])
    @user_emails = User.where.not(id: current_user.id || @wiki.users.pluck(:id)).map(&:email)
    authorize @wiki
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki

    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki page. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki page."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    extensions = {
     fenced_code_blocks: true,
     autolink: true,
     superscript: true,
     disable_indented_code_blocks: true,
     strikethrough: true,
     underline: true,
     highlight: true,
     quote: true,
     footnotes: true
   }

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions)
    markdown.render(text).html_safe
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <% if current_user.standard? %>
    <h4>Create your own wikis, for a one time $15 upgrade to a Premium account!</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% else %>
    <h4>You already are a Premium Member!  Congratulations!!!!</h4>
  <% end %>
<% end %>

app/views/collaborators/_collaborator_form.html.erb
<div class="container-fluid">
  <div class="row">
    <% if current_user.admin? || current_user.premium? %>
      <div class='field'>
        <%= form_for [@wiki, Collaborator.new] do |f| %>
          <%= f.label :collaborators %>
          <%= f.select :user, options_for_select(@user_emails, :selected => params[:user]) %>
          <%= f.submit 'Save' %>
        <% end %>
        <% if @wiki.users.any? %>
          <h3>Current collaborators</h3>
          <% @wiki.users.each do |user| %>
            <p><%= user.email %>
            | <%= link_to "x", wiki_collaborator_path(user_id: @user.id, wiki_id: @wiki.id), method: :delete %>
          </p>
          <% end %>
        <% end %>
      </div>
    <% else %>
        <h3>Current collaborators</h3>
        <% @wiki.users.each do |user| %>
          <% if user.email == current_user.email %>
            <p><%= current_user.email %>
            | <%= link_to "x", wiki_collaborator_path(user_id: @user.id, wiki_id: @wiki.id), method: :delete %>
            </p>
          <% end %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/downgrade/new.html.erb
<% if current_user.premium? %>
  <h4>Downgrade to Standard. <br>
  <small>You will be required to pay $15 to get your premium status back and your private wiki's will become public</small></h4>
  <%= link_to "Downgrade Your Account", downgrade_path, method: :post, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>
<% else %>
  <h4>You are already a Standard Member! Congratulations!!!</h4>
<% end %>

app/views/downgrades/new.html.erb
<% if current_user.premium? %>
  <h4>Downgrade to Standard. <br>
  <small>You will be required to pay $15 to get your premium status back and your private wiki's will become public</small></h4>
  <%= link_to "Downgrade Your Account", downgrades_path, method: :post, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>
<% else %>
  <h4>You are already a Standard Member! Congratulations!!!</h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', "https://cdnjs.cloudflare.com/ajax/libs/showdown/1.7.1/showdown.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", blocipedia_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <br>
            <div class="pull-right">
            <% if current_user.standard? %>
              <%= link_to "Upgrade your account to Premium", new_charge_path, :class => 'navbar-link' %>
            <% elsif current_user.premium? %>
              <%= link_to "Downgrade your account to Standard", new_downgrade_path, :class => 'navbar-link' %>
            <% end %>
            </div>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link  user_sign_up'  %> or
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
<h1 class="text-center">BLOCIPEDIA<h1>
  <p class="text-center"><strong>Become a part of a community!</strong></p>
</div>

app/views/wikis/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for @wiki do |f| %>
      <% if @wiki.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
          <ul>
            <% @wiki.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        <small>
          <div class="text-right">
            hover over text for syntax examples:
            <strong title="**bold**">bold</strong>
            <em title="<em>italic</em>">italic</em>
            <q title="<q>quote</q>">quote</q>
            <mark title="<mark>highlight</mark>">highlight</mark>
            <u title="_underline_">underline</u>
            <s title="~~strikethrough~~">strike</s>
            <small title="footnote^1 + ^1:footnote">footnotes</small>
          </div>
        </small>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="checkbox">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> <strong>Private wiki</strong>
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
        <%= link_to 'Cancel', wikis_path, class: 'btn btn-cancel' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<div class="container-fluid">
  <div class="make-row">
    <div class="row">
      <div class="col-md-8">
        <h1>Edit Wiki</h1>
        <% if current_user.admin? || current_user.premium? || @wiki.users.include?(current_user) %>
          <%= render partial: 'collaborators/collaborator_form' %>
        <% end %>
        <%= render 'form' %>
      </div>
      <div class="col-md-4">
        <h1 style="color:steelblue", class="text-center"> Live Preview </h1>
        <p id="wiki_preview"></p>
      </div>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>Wikis
        <% if user_signed_in? %>
          <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
        <% end %>
      </h1>
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to wiki.title, wiki %>
            </h4>
            <small>
              <%= markdown(wiki.body) %>
            </small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <h1>New Wiki</h1>
      <%= render 'form' %>
    </div>

    <div class="col-md-4">
      <h1 style="color:steelblue" class="text-center"> Live Preview </h1>
        <p id="wiki_preview"></p>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1 class="text-center"><%= @wiki.title %></h1>
    <p><%= markdown(@wiki.body) %></p>
  </div>
    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
    </div>
</div>